language: node_js
node_js:
  - "0.10"
cache:
  directories:
    - node_modules
before_script:
  - npm install flex-sdk

deploy:
  provider: releases
  api-key: oauth
  file: "ocm.swf"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true